version: '3.8'

services:
  server:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  web:
    build: ./web
    container_name: web
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - server
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge