version: '3.8'

services:
  server:
    build: ./server
    container_name: server
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - app-network

  web:
    build: ./web
    container_name: web
    environment:
      - VITE_SERVER_URL=/
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge