version: '3'

services:
  server:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    restart: unless-stopped

  web:
    build: ./web
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped
